name: Deploy to Hostinger
on: [push]
jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.the5amclub.online
          username: u488679753.mnijhara
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/public_html/
          local-dir: ./out/
          dangerous-clean-slate: true
